default_stages: [ pre-commit, manual ]

repos:
  # Code formatter
  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --config
          - .code_quality/pyproject_black.toml
  # Style guide enforcement
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - --config=.code_quality/.flake8

  # Static code analyser
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.3
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args:
          - --rcfile=.code_quality/.pylintrc

  # Common security issues analysis
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args:
          - -c
          - .code_quality/bandit.yaml

  # Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args:
          - --config-file=.code_quality/mypy.ini
        additional_dependencies:
          - types-PyMySQL
          - types-requests

  # Conventional commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ ]
